spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/spotifydb}
spring.datasource.username=${DB_USERNAME:spotify_user}
spring.datasource.password=${DB_PASSWORD:spotify_pass}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
server.port=${SERVER_PORT:8086}
spring.application.name=listener-service

# Eureka Client Configuration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
# URL for history/stats service (used to decouple history storage). In Docker compose this will be
# provided as environment variable `HISTORY_SERVICE_URL` and typically points to http://history-service:8088
history.service.url=${HISTORY_SERVICE_URL:http://history-service:8088}
